# Generated by Django 5.2.13 on 2026-05-17 18:23

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_images_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(),
        ),
    ]
