# Generated by Django 5.2.14 on 2026-05-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_long_description_place_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description_short',
        ),
    ]
