# Generated by Django 5.2.14 on 2026-05-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_description_long_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['order'], name='places_imag_order_7dcdfe_idx'),
        ),
    ]
